# Generated by Django 5.2.4 on 2025-07-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_id', models.PositiveIntegerField(verbose_name='شناسه ووکامرس')),
                ('status', models.CharField(max_length=50, verbose_name='وضعیت سفارش')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ کل')),
                ('created_at_in_wc', models.DateTimeField(verbose_name='زمان ایجاد در ووکامرس')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.store')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at_in_wc'],
                'unique_together': {('store', 'woocommerce_id')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_id', models.PositiveIntegerField(verbose_name='شناسه ووکامرس')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, verbose_name='اسلاگ')),
                ('permalink', models.URLField(verbose_name='لینک محصول')),
                ('status', models.CharField(default='publish', max_length=20, verbose_name='وضعیت')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت')),
                ('regular_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت اصلی')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت فروش ویژه')),
                ('on_sale', models.BooleanField(default=False, verbose_name='در فروش ویژه؟')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='تعداد کل فروش')),
                ('stock_quantity', models.IntegerField(blank=True, null=True, verbose_name='موجودی انبار')),
                ('stock_status', models.CharField(default='instock', max_length=20, verbose_name='وضعیت موجودی')),
                ('created_at_in_wc', models.DateTimeField(verbose_name='زمان ایجاد در ووکامرس')),
                ('updated_at_in_wc', models.DateTimeField(verbose_name='زمان به\u200cروزرسانی در ووکامرس')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.store')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-total_sales'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_product_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت در زمان خرید')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.product')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_id', models.PositiveIntegerField(verbose_name='شناسه ووکامرس')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, verbose_name='اسلاگ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.store')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محصول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصولات',
                'unique_together': {('store', 'woocommerce_id')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.productcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'woocommerce_id')},
        ),
    ]
