# Generated by Django 5.2.4 on 2025-07-30 05:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام تست')),
                ('variable', models.CharField(choices=[('PRICE', 'قیمت'), ('NAME', 'عنوان محصول')], max_length=20, verbose_name='متغیر مورد تست')),
                ('control_value', models.CharField(help_text='مقدار اصلی یا کنترل', max_length=255)),
                ('variant_value', models.CharField(help_text='مقدار جدید برای تست', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تست A/B',
                'verbose_name_plural': 'تست\u200cهای A/B',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_apikey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='شناسه مشتری (IP یا شناسه از سایت شما)', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'unique_together': {('owner', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='ABTestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_shown', models.CharField(choices=[('CONTROL', 'کنترل'), ('VARIANT', 'متغیر جدید')], max_length=20)),
                ('event_type', models.CharField(choices=[('VIEW', 'نمایش'), ('CONVERSION', 'تبدیل (خرید)')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_events', to='core.abtest')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_events', to='core.customer')),
            ],
            options={
                'verbose_name': 'رویداد تست A/B',
                'verbose_name_plural': 'رویدادهای تست A/B',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_otpcode', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_from_site', models.CharField(default='unknown', help_text='شناسه محصول در سایت شما', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('page_url', models.URLField(max_length=1024)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(default='عمومی', max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'unique_together': {('owner', 'product_id_from_site')},
            },
        ),
        migrations.AddField(
            model_name='abtest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='core.product'),
        ),
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VIEW', 'بازدید محصول'), ('ADD_TO_CART', 'افزودن به سبد'), ('PURCHASE', 'خرید نهایی')], default='VIEW', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.product')),
            ],
            options={
                'verbose_name': 'رویداد محصول',
                'verbose_name_plural': 'رویدادهای محصولات',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('LOW_VIEW', 'بازدید کم'), ('HIGH_VIEW_LOW_ADD', 'بازدید بالا، افزودن به سبد کم'), ('POPULAR_ITEM', 'محصول محبوب'), ('LOW_STOCK', 'موجودی کم'), ('HIGH_DISCOUNT', 'تخفیف بالا'), ('AI_GENERATED', 'پیشنهاد هوش مصنوعی')], max_length=30)),
                ('text', models.TextField(verbose_name='متن پیشنهاد')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_recommendations', to='core.product')),
            ],
            options={
                'verbose_name': 'پیشنهاد',
                'verbose_name_plural': 'پیشنهادات',
            },
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(unique=True, verbose_name='آدرس سایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('api_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='core.apikey')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
