# Generated by Django 5.2.4 on 2025-07-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productevent',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='event_type',
            field=models.CharField(choices=[('VIEW', 'بازدید محصول'), ('ADD_TO_CART', 'افزودن به سبد'), ('PURCHASE', 'خرید نهایی')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(choices=[('LOW_VIEW', 'بازدید کم'), ('HIGH_VIEW_LOW_ADD', 'بازدید بالا، افزودن به سبد کم'), ('POPULAR_ITEM', 'محصول محبوب'), ('LOW_STOCK', 'موجودی کم'), ('HIGH_DISCOUNT', 'تخفیف بالا'), ('AI_GENERATED', 'پیشنهاد هوش مصنوعی')], max_length=30),
        ),
    ]
