# Generated by Django 5.2.4 on 2025-07-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_category_product_discount_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(choices=[('LOW_VIEW', 'بازدید کم'), ('HIGH_VIEW_LOW_ADD', 'بازدید بالا، افزودن به سبد کم'), ('POPULAR_ITEM', 'محصول محبوب'), ('LOW_STOCK', 'موجودی کم'), ('HIGH_DISCOUNT', 'تخفیف بالا'), ('AI_GENERATED', 'پیشنهاد هوش مصنوعی'), ('DYNAMIC_PRICING', 'قیمت\u200cگذاری پویا')], max_length=30),
        ),
    ]
