# Generated by Django 5.2.4 on 2025-07-26 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_recommendation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(unique=True, verbose_name='آدرس سایت')),
                ('site_name', models.CharField(max_length=255, verbose_name='نام سایت')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='نام کاربری سایت')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='رمز عبور سایت')),
                ('api_key', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کلید API')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سایت کاربر',
                'verbose_name_plural': 'سایت\u200cهای کاربران',
            },
        ),
    ]
