# Generated by Django 5.2.4 on 2025-07-24 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id_woocommerce', models.IntegerField(unique=True, verbose_name='شناسه سفارش در ووکامرس')),
                ('customer_name', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ کل سفارش')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ ثبت سفارش')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('product_id_woocommerce', models.IntegerField(unique=True, verbose_name='شناسه محصول در ووکامرس')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='موجودی انبار')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت در زمان خرید')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='app.OrderItem', to='app.product', verbose_name='محصولات'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField(verbose_name='متن پیشنهاد')),
                ('reason', models.CharField(help_text='مثال: کاهش فروش، موجودی رو به اتمام', max_length=255, verbose_name='دلیل پیشنهاد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='محصول مرتبط')),
            ],
        ),
    ]
