# Generated by Django 5.2.4 on 2025-07-21 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('site_url', models.URLField(help_text='مثال: https://my-shop.com', unique=True, verbose_name='آدرس سایت ها')),
                ('woocommerce_consumer_key', models.CharField(max_length=255, verbose_name='کلید ووکامرس ')),
                ('woocommerce_consumer_secret', models.CharField(max_length=255, verbose_name='کلید امنیتی ووکامرس ')),
                ('is_active', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن، همگام\u200cسازی و تحلیل برای این فروشگاه انجام نمی\u200cشود.', verbose_name='اشتراک فعال ')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان همگام سازی موفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='صاحب فروشگاه')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
