# Generated by Django 5.2.4 on 2025-07-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplan_otpcode_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='آیا این یک پلن آزمایشی است که فقط یکبار به کاربر داده می\u200cشود؟'),
        ),
    ]
