# Generated by Django 5.2.4 on 2025-07-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(choices=[('SALES_DROP', 'افت فروش'), ('LOW_SALES', 'فروش پایین مزمن'), ('NO_SALES', 'بدون فروش'), ('HIGH_POTENTIAL', 'پتانسیل بالای فروش'), ('POOR_CONVERSION', 'نرخ تبدیل پایین'), ('RELATED_PRODUCT_OPP', 'فرصت فروش همراه'), ('STOCK_ISSUE', 'مشکل موجودی انبار')], max_length=50, verbose_name='کد دلیل')),
                ('suggestion', models.TextField(help_text='یک اقدام عملی که فروشنده باید انجام دهد.', verbose_name='متن پیشنهاد')),
                ('details', models.JSONField(default=dict, help_text='داده\u200cهایی که منجر به این پیشنهاد شده\u200cاند، برای نمایش در UI.', verbose_name='جزئیات تحلیلی')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('seen', 'مشاهده شده'), ('actioned', 'اقدام شده'), ('dismissed', 'نادیده گرفته شده')], db_index=True, default='new', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'پیشنهاد',
                'verbose_name_plural': 'پیشنهادها',
                'ordering': ['-created_at'],
            },
        ),
    ]
