# Generated by Django 5.2.4 on 2025-07-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('analysis', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.product'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.store'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('product', 'reason_code', 'status')},
        ),
    ]
